// HelloSW.idl : HelloSW.exe 的类型库源

// 此文件将由 MIDL 编译器处理以产生
// 类型库(HelloSW.tlb)。

[ uuid(18C04EBC-4ECB-429A-B4B3-79609EC81405), version(1.0) ]
library HelloSW
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  CHelloSWDoc 的主调度接口
	
	[ uuid(7864ECEF-A3A5-4679-9AB2-813A1B3291AF) ]
	dispinterface IHelloSW
	{
		properties:
			
		methods:
	};

	//  CHelloSWDoc 的类信息
	
	[ uuid(FA6486C3-9619-411E-B166-E9CCE569F1D8) ]
	coclass CHelloSWDoc
	{
		[default] dispinterface IHelloSW;
	};
};
